// Dev-time generation script. Run manually with:
//   node scripts/generate-places.mjs
//
// Reads the `world-countries` and `all-the-cities` devDependencies (never
// shipped to the browser bundle) and writes a compact, tuple-encoded, static,
// committed TypeScript data file at src/data/places.ts for use by the
// place-search-add-memory feature's Place_Lookup_Service. This script is NOT
// part of `npm run build`.

import countries from 'world-countries';
import cities from 'all-the-cities';
import { writeFileSync } from 'fs';

// Countries: every entry with a valid latlng, regardless of `independent`
// status, since city records reference country codes and need a name
// available for every possible code, and countries are also included as
// their own searchable record kind (Requirement 5.1).
const countryRecords = countries
  .filter((c) => Array.isArray(c.latlng) && c.latlng.length === 2)
  .map((c) => [
    /* kind */ 'country',
    /* name */ c.name.common,
    /* countryCode */ c.cca2,
    /* lat */ c.latlng[0],
    /* lng */ c.latlng[1],
    /* population */ 0,
  ]);

const countryNames = {};
for (const c of countries) {
  countryNames[c.cca2] = c.name.common;
}

// Cities/towns: population >= 500, meaningfully richer than geoLabels.ts's
// >= 300,000 floor (Requirement 5.1).
const cityRecords = cities
  .filter(
    (c) =>
      typeof c.population === 'number' &&
      c.population >= 500 &&
      c.loc &&
      Array.isArray(c.loc.coordinates) &&
      c.loc.coordinates.length === 2
  )
  .map((c) => [
    /* kind */ 'city',
    /* name */ c.name,
    /* countryCode */ c.country,
    /* lat */ c.loc.coordinates[1],
    /* lng */ c.loc.coordinates[0],
    /* population */ c.population,
  ]);

const placeRecords = [...countryRecords, ...cityRecords];

const output = `// AUTO-GENERATED by scripts/generate-places.mjs. Do not hand-edit.
// Regenerate with: node scripts/generate-places.mjs

export type PlaceRecordKind = 'country' | 'city';

/** [kind, name, countryCode, lat, lng, population] */
export type PlaceRecord = [PlaceRecordKind, string, string, number, number, number];

export const placeRecords: PlaceRecord[] = ${JSON.stringify(placeRecords)};

/** ISO 3166-1 alpha-2 code -> country common name, for the "detail" field. */
export const countryNames: Record<string, string> = ${JSON.stringify(countryNames, null, 2)};
`;

writeFileSync('src/data/places.ts', output);

console.log(
  `Generated ${countryRecords.length} countries and ${cityRecords.length} cities (${placeRecords.length} total place records).`
);
